/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      { source: '/comparisons/concrete-vs-plastic-vs-fiberglass', destination: '/comparisons/concrete-vs-plastic-vs-fiberglass-septic-tanks', permanent: true },
      { source: '/articles', destination: '/guides', permanent: true },
      { source: '/articles/septic-maintenance-checklist', destination: '/maintenance/septic-system-maintenance-checklist', permanent: true },
      { source: '/articles/septic-inspection-cost', destination: '/cost-guides/septic-inspection-cost', permanent: true },
      { source: '/articles/signs-drainfield-is-failing', destination: '/problems/drainfield-failing', permanent: true },
      { source: '/articles/septic-system-maintenance-checklist', destination: '/maintenance/septic-system-maintenance-checklist', permanent: true },
      { source: '/cost-guides/septic-tank-pumping-cost', destination: '/articles/septic-tank-pumping-cost', permanent: true },
      { source: '/articles/drainfield-replacement-cost', destination: '/cost-guides/drainfield-replacement-cost', permanent: true },
      { source: '/articles/slow-drains-septic-system', destination: '/problems/slow-drains', permanent: true },
      { source: '/articles/septic-tank-backing-up', destination: '/problems/tank-backing-up', permanent: true },
      { source: '/articles/best-septic-safe-laundry-detergent', destination: '/reviews/best-septic-safe-laundry-detergent', permanent: true },
      { source: '/articles/does-insurance-cover-septic', destination: '/articles/does-insurance-cover-septic-repair-replacement', permanent: true },
      { source: '/articles/do-septic-tank-additives-work', destination: '/articles/septic-tank-additives', permanent: true },
      { source: '/problems/slow-drains-on-septic-system', destination: '/problems/slow-drains', permanent: true },
      { source: '/articles/what-not-to-flush-septic', destination: '/articles/what-can-cannot-flush-septic-system', permanent: true },
      { source: '/septic-tank-pumping-cost', destination: '/articles/septic-tank-pumping-cost', permanent: true },
      { source: '/how-to-find-your-septic-tank', destination: '/articles/how-to-find-your-septic-tank', permanent: true },
      { source: '/articles/does-insurance-cover-septic-repair', destination: '/articles/does-insurance-cover-septic-repair-replacement', permanent: true },
      { source: '/articles/septic-smell-in-yard', destination: '/problems/septic-smell-in-yard', permanent: true },
      { source: '/articles/septic-dos-and-donts', destination: '/guides/septic-dos-and-donts', permanent: true },
      { source: '/cost-guides/installation-cost', destination: '/cost-guides/septic-system-installation-cost', permanent: true },
      { source: '/problems/septic-smell-yard', destination: '/problems/septic-smell-in-yard', permanent: true },
      { source: '/cost-guides/septic-repair-cost', destination: '/cost-guides/septic-system-repair-cost', permanent: true },
      { source: '/selling-a-home/septic-system', destination: '/guides/selling-home-with-septic-system', permanent: true },
      { source: '/articles/best-septic-tank-risers', destination: '/reviews/best-septic-tank-risers', permanent: true },
      { source: '/articles/best-drain-cleaners-septic-systems', destination: '/reviews/best-drain-cleaners-for-septic', permanent: true },
      { source: '/articles/best-toilet-paper-septic-systems', destination: '/reviews/best-toilet-paper-for-septic', permanent: true },
      { source: '/articles/septic-tank-size-guide', destination: '/guides/septic-tank-size-guide', permanent: true },
      { source: '/does-insurance-cover-septic-repair-replacement', destination: '/articles/does-insurance-cover-septic-repair-replacement', permanent: true },
      { source: '/comparisons/aerobic-vs-anaerobic-septic', destination: '/comparisons/aerobic-vs-anaerobic-septic-systems', permanent: true },
      { source: '/cost-guides/inspection-cost', destination: '/cost-guides/septic-inspection-cost', permanent: true },
      { source: '/reviews/best-drain-cleaners', destination: '/reviews/best-drain-cleaners-for-septic', permanent: true },
      { source: '/articles/best-septic-safe-cleaning-products', destination: '/reviews/best-septic-safe-cleaning-products', permanent: true },
      { source: '/articles/what-can-you-flush', destination: '/articles/what-can-cannot-flush-septic-system', permanent: true },
      { source: '/guides/selling-home-with-septic', destination: '/guides/selling-home-with-septic-system', permanent: true },
      { source: '/what-can-cannot-flush-septic-system', destination: '/articles/what-can-cannot-flush-septic-system', permanent: true },
      { source: '/problems/overflow-after-rain', destination: '/problems/septic-overflow-after-rain', permanent: true },
      { source: '/cost-guides/repair-cost', destination: '/cost-guides/septic-system-repair-cost', permanent: true },
      { source: '/articles/septic-system-repair-cost', destination: '/cost-guides/septic-system-repair-cost', permanent: true },
      { source: '/buying-a-home/septic-system', destination: '/guides/buying-home-with-septic', permanent: true },
      { source: '/articles/how-long-septic-system-lasts', destination: '/articles/how-long-does-a-septic-system-last', permanent: true },
      { source: '/problems/slow-drains-septic', destination: '/problems/slow-drains', permanent: true },
      { source: '/problems/septic-smell-in-house', destination: '/problems/septic-smell-inside-house', permanent: true },
      { source: '/problems/septic-tank-backing-up', destination: '/problems/tank-backing-up', permanent: true },
      { source: '/guides/maintenance-guide', destination: '/maintenance', permanent: true },
      { source: '/articles/maintenance/septic-system-maintenance-checklist', destination: '/maintenance/septic-system-maintenance-checklist', permanent: true },
      { source: '/guides/find-your-septic-tank', destination: '/articles/how-to-find-your-septic-tank', permanent: true },
      { source: '/articles/guides/buying-home-with-septic', destination: '/guides/buying-home-with-septic', permanent: true },
      { source: '/articles/guides/septic-tank-size-guide', destination: '/guides/septic-tank-size-guide', permanent: true },
      { source: '/reviews/best-septic-treatments', destination: '/reviews/best-septic-tank-treatments', permanent: true },
    ]
  },
}

module.exports = nextConfig