export interface Article {
  title: string
  description: string
  slug: string
  category: string
  readTime: string
  image?: string
}

export const articles: Article[] = [
  {
    title: 'The Complete Guide to Septic Systems: How They Work, Types, and What Every Homeowner Needs to Know',
    description: 'Over 21 million homes in the US rely on septic systems. Learn how they work, the different types, maintenance costs, and warning signs of failure.',
    slug: 'complete-septic-guide',
    category: 'Guide',
    readTime: '25 min read',
    image: '/septic1.jpg',
  },
  {
    title: 'Septic Tank Pumping Cost 2026: What You\'ll Actually Pay',
    description: 'The average septic tank pumping costs $300 to $600. Real pricing by tank size, region, hidden fees to watch for, and the questions to ask before hiring.',
    slug: 'septic-tank-pumping-cost',
    category: 'Cost Guide',
    readTime: '18 min read',
    image: '/pumpingcostguide.jpg',
  },
  {
    title: 'How Often Should You Pump Your Septic Tank? 2026 Schedule',
    description: 'Find your exact septic pumping schedule by tank size and household size. EPA-based table, factors that change your interval, and how to measure when your tank actually needs pumping.',
    slug: 'how-often-pump-septic-tank',
    category: 'Guide',
    readTime: '20 min read',
    image: '/septicpump3.jpg',
  },
  {
    title: 'What You Can and Cannot Flush with a Septic System: The Complete List',
    description: 'The complete list of what is safe to flush, what should never be flushed, and what to keep out of your drains. Protect your septic tank and drainfield from costly damage.',
    slug: 'what-can-cannot-flush-septic-system',
    category: 'Guide',
    readTime: '18 min read',
    image: '/flushing.jpg',
  },
  {
    title: 'Septic Tank Backing Up? Causes, Fixes, and When to Call a Pro',
    description: 'Learn why your septic tank is backing up, how to diagnose the problem, emergency steps, and when professional help is needed. Complete troubleshooting guide.',
    slug: 'problems/tank-backing-up',
    category: 'Problem',
    readTime: '22 min read',
    image: '/1.jpg',
  },
  {
    title: 'Signs Your Drainfield Is Failing: Warning Signs, Causes & What to Do',
    description: 'Learn the 7 warning signs of drainfield failure from earliest to latest. Understand what causes drainfield problems, which ones are fixable, and when you need a full replacement.',
    slug: 'problems/drainfield-failing',
    category: 'Problem',
    readTime: '20 min read',
    image: '/drainfieldexample.jpg',
  },
  {
    title: 'Septic System Installation Cost 2026: Complete Price Breakdown by Type',
    description: 'A new septic system costs $3,000 to $20,000 installed. Complete price breakdown by system type, cost components, tank materials, hidden costs, and how to save money.',
    slug: 'cost-guides/septic-system-installation-cost',
    category: 'Cost Guide',
    readTime: '25 min read',
    image: '/costguide.jpg',
  },
  {
    title: 'Septic Smell in Your Yard? 8 Causes and How to Fix Each One',
    description: 'A septic smell in your yard is caused by hydrogen sulfide and methane gas escaping from your septic system. Learn the 8 most common causes, how to diagnose each one, and the specific fix and cost for each.',
    slug: 'problems/septic-smell-in-yard',
    category: 'Problem',
    readTime: '20 min read',
    image: '/badsepticsmell.jpg',
  },
  {
    title: 'Best Septic Tank Treatments 2025: Honest Reviews After Real Testing',
    description: 'We tested the top septic tank treatments and additives. See which products actually work, which are a waste of money, and what science says about bacterial and enzyme treatments.',
    slug: 'reviews/best-septic-tank-treatments',
    category: 'Review',
    readTime: '22 min read',
    image: '/septicsavor.jpg',
  },
  {
    title: 'Best Septic Tank Sludge Dissolver 2026: 4 Products That Actually Work',
    description: 'Most sludge dissolvers make claims they cannot keep. These four biological products reduce organic sludge safely — and we explain exactly when each one is and is not worth using.',
    slug: 'reviews/best-septic-tank-sludge-dissolver',
    category: 'Review',
    readTime: '18 min read',
    image: '/septicsludge.jpg',
  },
  {
    title: 'Concrete vs. Plastic vs. Fiberglass Septic Tanks: Full 2025 Comparison',
    description: 'Compare concrete, plastic, and fiberglass septic tanks side by side. Costs, lifespan, pros and cons, installation differences, and which material is best for your property.',
    slug: 'comparisons/concrete-vs-plastic-vs-fiberglass-septic-tanks',
    category: 'Comparison',
    readTime: '22 min read',
    image: '/fiberglassplasticconcret.jpg',
  },
    {
    title: 'Buying a Home with a Septic System: What to Know Before You Close',
    description: 'A septic inspection before closing costs $300-$1,000 and can reveal problems costing $5,000-$25,000 to fix. Learn what to ask, what to inspect, and how to negotiate.',
    slug: 'guides/buying-home-with-septic',
    category: 'Guide',
    readTime: '25 min read',
    image: '/septicinspection.jpg',
  },
    {
      title: 'Best Toilet Paper for Septic Systems 2026: Tested and Ranked',
      description: 'The best toilet paper for septic systems dissolves fast, skips the chemicals, and protects your tank. We tested and ranked the top septic-safe brands so you know exactly what to buy.',
      slug: 'reviews/best-toilet-paper-for-septic',
      category: 'Review',
      readTime: '18 min read',
      image: '/toiletpaper.jpg',
  },
  {
    title: 'How to Find Your Septic Tank: 5 Methods That Work',
    description: 'Your septic tank is buried 5 to 25 feet from your house. Learn 5 proven methods to locate it, from checking records to using a soil probe, plus what to do after you find it.',
    slug: 'how-to-find-your-septic-tank',
    category: 'Guide',
    readTime: '18 min read',
        image: '/how to find your septic tank.jpg',
    },
  {
    title: 'Septic System Repair Cost 2026: Every Repair Priced Out',
    description: 'Septic system repairs cost $600 to $3,000 on average. Complete pricing for every repair from $50 filter cleaning to $15,000 drainfield replacement.',
    slug: 'cost-guides/septic-system-repair-cost',
    category: 'Cost Guide',
    readTime: '22 min read',
    image: '/septic repair.jpg',
  },
    {
    title: 'Does Insurance Cover Septic System Repair or Replacement?',
    description: 'Standard homeowners insurance does not cover most septic repairs. Learn what is and isn\'t covered, which add-on coverages are worth buying, and how to protect yourself financially.',
    slug: 'does-insurance-cover-septic-repair-replacement',
    category: 'Guide',
    readTime: '20 min read',
    image: '/insurance.jpg',
  },
    {
    title: 'Aerobic vs Anaerobic Septic Systems: Differences, Costs, and Which You Need',
    description: 'Anaerobic septic systems cost $3,000 to $8,000. Aerobic systems cost $10,000 to $20,000. Complete comparison of costs, maintenance, pros, cons, and which system your property requires.',
    slug: 'comparisons/aerobic-vs-anaerobic-septic-systems',
    category: 'Comparison',
    readTime: '18 min read',
    image: '/aerovsanarobichero.jpg',
  },
    {
    title: 'Best Septic Tank Risers 2026: The Upgrade That Pays for Itself',
    description: 'A septic tank riser costs $100 to $400 and eliminates the $50 to $200 digging fee at every service visit. Compare the best riser kits, learn how to choose the right size, and whether to DIY or hire a pro.',
    slug: 'reviews/best-septic-tank-risers',
    category: 'Review',
    readTime: '18 min read',
    image: '/riser.jpg',
  },
    {
    title: 'Drainfield Replacement Cost 2026: What to Expect and How to Save',
    description: 'Drainfield replacement costs $5,000 to $15,000 for a conventional system. Mound system replacement costs $10,000 to $20,000. Complete cost breakdown, rejuvenation vs replacement, and how to save money.',
    slug: 'cost-guides/drainfield-replacement-cost',
    category: 'Cost Guide',
    readTime: '20 min read',
    image: '/drainfieldcost.jpg',
  },
    {
      title: 'Septic System vs Sewer: Costs, Pros and Cons, and Which Is Better',
      description: 'Septic costs $3,500 to $12,000 to install with no monthly bill. Sewer costs $1,500 to $6,000 plus $15 to $150/month. Complete 20-year cost comparison.',
      slug: 'comparisons/septic-vs-sewer',
      category: 'Comparison',
      readTime: '22 min read',
      image: '/heroseptic-sewer.jpg',
    },
  {
    title: 'Septic Overflow After Rain? Why It Happens and How to Fix It',
    description: 'Septic overflow after rain is caused by groundwater saturating your drainfield, stormwater entering your tank, or a system near capacity. Learn the 5 mechanisms, emergency steps, and long-term fixes.',
    slug: 'problems/septic-overflow-after-rain',
    category: 'Problem',
    readTime: '18 min read',
    image: '/septicafterrain.jpg',
      },
      {
      title: 'Slow Drains with a Septic System: 5 Causes and How to Fix Each One',
    description: 'Slow drains with a septic tank? Learn the 5 most common causes from P-trap venting to full tanks, plus a one-fixture test to find the problem fast.',
    slug: 'problems/slow-drains',
    category: 'Problem',
    readTime: '20 min read',
    image: '/slowdrainseptic.jpg',
  },
    {
    title: 'Septic Inspection Cost 2026: What Each Type Costs and What\u2019s Actually Included',
    description: 'A septic inspection costs $150 to $650 depending on the type. Compare visual, routine, comprehensive, and real estate inspection costs, what each includes, hidden fees, and how to choose an inspector.',
    slug: 'cost-guides/septic-inspection-cost',
    category: 'Cost Guide',
    readTime: '22 min read',
    image: '/septic inspection.jpg',
  },
  {
    title: 'Best Drain Cleaners for Septic Systems (2026): 5 Safe Picks That Won\u2019t Kill Your Tank',
    description: 'The best drain cleaner for a septic system is an enzyme-based product that digests clogs without harming tank bacteria. Compare 5 septic-safe picks.',
    slug: 'reviews/best-drain-cleaners-for-septic',
    category: 'Review',
    readTime: '20 min read',
    image: '/Drain cleaners (septic) .jpg',
  },
    {
    title: 'Best Septic System Alarms (2026): 5 Picks That Prevent Expensive Disasters',
    description: 'A septic system alarm costs $30 to $200 and warns you when water levels get dangerously high. Compare the 5 best septic alarms, how they work, and which type fits your system.',
    slug: 'reviews/best-septic-system-alarms',
    category: 'Review',
    readTime: '22 min read',
    image: '/septicalarms.jpg',
  },
  {
    title: 'Septic System Maintenance Checklist: The Complete Seasonal Guide for Homeowners',
    description: 'The four essential septic maintenance tasks, seasonal checklists for spring, summer, fall, and winter, maintenance by system type, DIY vs pro tasks, and warning signs that mean call a pro now.',
    slug: 'maintenance/septic-system-maintenance-checklist',
    category: 'Maintenance',
    readTime: '25 min read',
    image: '/septicmaintaince.jpg',
  },
    {
    title: 'Septic System Dos and Don\u2019ts: The Rules That Protect a $15,000 Investment',
    description: 'Every do and don\u2019t for septic system owners with specific damage and repair costs for each violation. Flushing rules, chemical warnings, drainfield protection, and daily habits.',
    slug: 'guides/septic-dos-and-donts',
    category: 'Guide',
    readTime: '30 min read',
    image: '/dos and donts.jpg',
  },
    {
    title: 'Septic Tank Size Guide: What Size Septic Tank Do You Need?',
    description: 'The minimum septic tank size for most homes is 1,000 gallons. Size by bedroom count, how to calculate your actual need, when to go bigger, and how tank size affects pumping cost.',
    slug: 'guides/septic-tank-size-guide',
    category: 'Guide',
    readTime: '25 min read',
    image: '/septictanksize.jpg',
  },
    {
    title: 'How Long Does a Septic System Last? Lifespan by Component, Material & Maintenance',
    description: 'A septic system lasts 20 to 30 years on average. Concrete tanks last 40-50 years, drainfields 20-30 years. Lifespan by every component, material, and maintenance level.',
    slug: 'how-long-does-a-septic-system-last',
    category: 'Article',
    readTime: '30 min read',
    image: '/tanklast.jpg',
  },
  {
    title: 'Garbage Disposal and Septic Systems: Can You Use One Safely? 2026 Guide',
    description: 'Can you use a garbage disposal with a septic system? Yes, but it depends on how you use it. Research-backed guide covering costs, safe foods, rules, and septic-specific disposal models.',
    slug: 'guides/garbage-disposal-septic-systems',
    category: 'Guide',
    readTime: '20 min read',
    image: '/garbage disposal .jpg',
  },
  {
    title: 'Septic to Sewer Conversion Cost 2026: Complete Price Breakdown',
    description: 'Septic to sewer conversion costs $5,000 to $15,000 in 2026, with a national average of $7,000 to $10,000. Full cost breakdown, when conversion makes financial sense, grants, and step-by-step process.',
    slug: 'cost-guides/septic-to-sewer-conversion-cost',
    category: 'Cost Guide',
    readTime: '22 min read',
    image: '/septictosewer.jpg',
  },
  {
    title: 'Best Septic-Safe Laundry Detergent 2026: Top 6 Picks Ranked',
    description: 'The best septic-safe laundry detergents in 2026, ranked by septic impact, cleaning power, and value. Seventh Generation, ECOS, Earth Breeze, and more tested and reviewed.',
    slug: 'reviews/best-septic-safe-laundry-detergent',
    category: 'Review',
    readTime: '20 min read',
    image: '/laundry.jpg',
  },
    {
    title: 'Selling a Home with a Septic System: The Complete 2026 Seller\u2019s Guide',
    description: 'Selling a home with a septic system requires a pre-sale inspection ($300\u2013$600), current pumping records, and proper disclosure. Complete guide to pre-listing preparation, disclosure requirements, negotiation strategies, and closing.',
    slug: 'guides/selling-home-with-septic-system',
    category: 'Guide',
    readTime: '25 min read',
    image: '/sellinghomeonseptic.jpg',
  },
    {
    title: 'Septic Smell Inside the House: 10 Causes and How to Fix Each One',
    description: 'A septic smell inside the house is caused by hydrogen sulfide and methane gas escaping from the septic system. Learn the 10 most common causes, how to diagnose each one, and the specific fix and cost for each.',
    slug: 'problems/septic-smell-inside-house',
    category: 'Problem',
    readTime: '22 min read',
    image: '/septicsmellhouse.jpg',
  },
    {
    title: 'Best Septic-Safe Cleaning Products 2026: Bathroom, Kitchen & Floor',
    description: 'The best septic-safe cleaning products use plant-based, biodegradable formulas that clean effectively without harming septic tank bacteria.',
    slug: 'reviews/best-septic-safe-cleaning-products',
    category: 'Review',
    readTime: '22 min read',
    image: '/cleanerssepticsafe.jpg',
  },
    {
    title: 'Septic System Winter Care 2026: How to Winterize Your Septic System',
    description: 'Septic system winter care covers winterizing pipes, tanks, and drainfields to prevent freezing and costly repairs.',
    slug: 'guides/septic-system-winter-care',
    category: 'Guide',
    readTime: '20 min read',
    image: '/septicwinter.jpg',
  },
    {
    title: 'Septic Tank Cleaning vs Pumping: What\u2019s the Difference and Which Do You Need?',
    description: 'Septic tank cleaning and pumping are not the same service. Learn the difference, when you need each, what each costs, and how to avoid paying for work you don\u2019t need.',
    slug: 'septic-tank-cleaning-vs-pumping',
    category: 'Article',
    readTime: '20 min read',
    image: '/septic pump.jpg',
  },
  {
    title: 'Do Septic Tank Additives Work? The Complete 2026 Guide',
    description: 'The EPA does not recommend septic additives for healthy systems. Here is exactly what each type does, what the research says, when a biological additive might actually help, and what to avoid entirely.',
    slug: 'septic-tank-additives',
    category: 'Article',
    readTime: '20 min read',
    image: '/septictanksadditives.jpg',
  },
  {
    title: 'Septic System Inspection Guide: What Happens, Step by Step',
    description: 'What actually happens during a septic inspection, what inspectors look for at each component, how to prepare your property, and how to read the report when it arrives.',
    slug: 'guides/septic-inspection-guide',
    category: 'Guide',
    readTime: '20 min read',
    image: '/septicinspectionguide.jpg',
  },
  {
    title: 'Mound Septic Systems: How They Work, When You Need One, and How to Maintain It',
    description: 'A mound septic system is required when soil depth, water table, or bedrock prevents a conventional drainfield. How they work, what they cost to maintain, and how long they last.',
    slug: 'guides/mound-septic-system',
    category: 'Guide',
    readTime: '20 min read',
    image: '/moundsystem.jpg',
  },
  {
    title: 'Water Softeners and Septic Systems: The Complete 2026 Guide',
    description: 'Can you use a water softener with a septic system? Research-backed guide covering salt loads, drain field impact, system selection, and maintenance best practices.',
    slug: 'guides/water-softener-septic-systems',
    category: 'Guide',
    readTime: '20 min read',
    image: '/water softener.jpg',
  },
  {
    title: 'Tree Roots in Your Septic System: Signs, Fixes, and How to Stop It Happening Again',
    description: 'Tree roots are one of the most common causes of septic system failure. Learn the warning signs, what roots do to your tank and drainfield, removal options, and which trees to avoid planting near a septic system.',
    slug: 'problems/tree-roots-septic-system',
    category: 'Problem',
    readTime: '25 min read',
    image: '/septictree.jpg',
  },
  {
    title: 'What to Plant Over and Around Your Septic System',
    description: 'The right plants help your drainfield work better. Exactly what to plant over the tank, drainfield, and mound, what to avoid, and the vegetable garden question answered honestly.',
    slug: 'guides/plants-septic-system',
    category: 'Guide',
    readTime: '22 min read',
    image: '/septicplanthero.jpg',
  },
]

export function searchArticles(query: string): Article[] {
  if (!query.trim()) return []
  const terms = query.toLowerCase().split(/\s+/)
  return articles.filter((article) => {
    const searchText = `${article.title} ${article.description} ${article.category}`.toLowerCase()
    return terms.every((term) => searchText.includes(term))
  })
}
